=== MaxHaertwig/CoMod/schema/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="model">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="class">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="attribute" minOccurs="1" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="id" type="uuid" use="required" />
                        <xs:attribute name="visibility" type="visibility" use="required" />
                        <xs:attribute name="type" type="dataType" use="required" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
                <xs:element name="operation" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                      <xs:element name="param" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="id" type="uuid" use="required" />
                              <xs:attribute name="type" type="dataType" use="required" />
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="uuid" use="required" />
                    <xs:attribute name="visibility" type="visibility" use="required" />
                    <xs:attribute name="returnType" type="returnType" use="required" />
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="uuid" use="required" />
            <xs:attribute name="x" type="xs:integer" use="required" />
            <xs:attribute name="y" type="xs:integer" use="required" />
            <xs:attribute name="extends" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="relationship">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="from" type="uuid" use="required" />
                <xs:attribute name="to" type="uuid" use="required" />
                <xs:attribute name="type" type="relationshipType" use="required" />
                <xs:attribute name="fromMulti" type="xs:string" />
                <xs:attribute name="toMulti" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="version" type="xs:string" use="required" />
      <xs:attribute name="uuid" type="uuid" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="uuid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="visibility">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public" />
      <xs:enumeration value="package" />
      <xs:enumeration value="protected" />
      <xs:enumeration value="private" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="dataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="integer" />
      <xs:enumeration value="real" />
      <xs:enumeration value="string" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="returnType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="void" />
      <xs:enumeration value="boolean" />
      <xs:enumeration value="integer" />
      <xs:enumeration value="real" />
      <xs:enumeration value="string" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="relationshipType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="aggregation" />
      <xs:enumeration value="composition" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MaxHaertwig/CoMod/schema/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<model version="1.0" uuid="6c84fb90-12c4-11e1-840d-7b25c5ee775a" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
  <class id="598e6db1-db45-4f98-ab18-0d79174a0d41" x="0" y="0">
    <name>Person</name>
    <attribute visibility="public" type="string">
      Name
    </attribute>
    <attribute visibility="private" type="integer">
      Age
    </attribute>
  </class>
  <class id="68bbd3a7-3bc9-4c09-885e-b278446fbd25" extends="598e6db1-db45-4f98-ab18-0d79174a0d41" x="0" y="100">
    <name>Student</name>
    <attribute visibility="public" type="string">
      Major
    </attribute>
    <operation visibility="protected" returnType="void">
      <name>study</name>
      <arg type="string">
        subject
      </arg>
      <arg type="integer">
        hours
      </arg>
    </operation>
  </class>
  <class id="027e019a-11dc-4fbb-bce8-03b3dc73de9d" x="100" y="100">
    <name>Book</name>
    <attribute visibility="public" type="string" />
  </class>
  <relationship from="68bbd3a7-3bc9-4c09-885e-b278446fbd25" to="027e019a-11dc-4fbb-bce8-03b3dc73de9d" fromMulti="1" toMulti="0..*" type="aggregation">
    has
  </relationship>
</model>
